[project]
name = "rose-cli"
version = "0.1.3"
description = "ROSE CLI - Command line interface for ROSE server"
readme = "README.md"
requires-python = ">=3.12,<4.0"
authors = [{ name = "Garden Variety AI" }]
license = { text = "MIT" }
keywords = ["llm", "ai", "cli", "client"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "typer>=0.16.0",
    "rich>=13.7.1",
    "httpx>=0.28.1",
    "cohere>=5.18.0",
    "openai>=1.88.0",
]

[project.scripts]
rose = "rose_cli.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["src/rose_cli"]
