"""initial schema

Revision ID: eb8ca7eaf12d
Revises:
Create Date: 2025-12-23 02:35:05.981705

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb8ca7eaf12d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("thread_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reasoning", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("meta", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("accepted_at", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.Integer(), nullable=True),
        sa.Column(
            "completion_id",
            sa.String(),
            sa.Computed(
                "json_extract(meta, '$.completion_id')",
            ),
            nullable=True,
        ),
        sa.Column(
            "lens_id",
            sa.String(),
            sa.Computed(
                "json_extract(meta, '$.lens_id')",
            ),
            nullable=True,
        ),
        sa.Column(
            "at_name",
            sa.String(),
            sa.Computed(
                "json_extract(meta, '$.at_name')",
            ),
            nullable=True,
        ),
        sa.Column(
            "object",
            sa.String(),
            sa.Computed(
                "json_extract(meta, '$.object')",
            ),
            nullable=True,
        ),
        sa.Column(
            "root_message_id",
            sa.String(),
            sa.Computed(
                "json_extract(meta, '$.root_message_id')",
            ),
            nullable=True,
        ),
        sa.Column(
            "parent_message_id",
            sa.String(),
            sa.Computed(
                "json_extract(meta, '$.parent_message_id')",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_accepted_at"), "messages", ["accepted_at"], unique=False)
    op.create_index("ix_messages_at_name", "messages", ["at_name"], unique=False)
    op.create_index("ix_messages_completion_id", "messages", ["completion_id"], unique=False)
    op.create_index(op.f("ix_messages_deleted_at"), "messages", ["deleted_at"], unique=False)
    op.create_index("ix_messages_lens_id", "messages", ["lens_id"], unique=False)
    op.create_index("ix_messages_object", "messages", ["object"], unique=False)
    op.create_index("ix_messages_parent_message_id", "messages", ["parent_message_id"], unique=False)
    op.create_index("ix_messages_root_message_id", "messages", ["root_message_id"], unique=False)
    op.create_index(op.f("ix_messages_thread_id"), "messages", ["thread_id"], unique=False)
    op.create_index(op.f("ix_messages_uuid"), "messages", ["uuid"], unique=True)
    op.create_table(
        "search_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("search_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("query", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("original_query", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("thread_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_search_events_created_at"), "search_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_search_events_event_type"), "search_events", ["event_type"], unique=False)
    op.create_index(op.f("ix_search_events_result_count"), "search_events", ["result_count"], unique=False)
    op.create_index(op.f("ix_search_events_search_mode"), "search_events", ["search_mode"], unique=False)
    op.create_index(op.f("ix_search_events_thread_id"), "search_events", ["thread_id"], unique=False)
    op.create_index("ix_search_events_type_created", "search_events", ["event_type", "created_at"], unique=False)
    op.create_index(op.f("ix_search_events_uuid"), "search_events", ["uuid"], unique=True)
    # ### end Alembic commands ###

    # FTS5 virtual table for full-text search
    op.execute("""
        CREATE VIRTUAL TABLE messages_fts USING fts5(
            content,
            root_message_id UNINDEXED,
            role UNINDEXED,
            model UNINDEXED,
            thread_id UNINDEXED,
            created_at UNINDEXED,
            tokenize = 'porter unicode61 remove_diacritics 2'
        )
    """)

    # Trigger: After INSERT - update FTS with latest message per conversation
    op.execute("""
        CREATE TRIGGER messages_ai AFTER INSERT ON messages BEGIN
            DELETE FROM messages_fts
            WHERE root_message_id = COALESCE(new.root_message_id, new.uuid);

            INSERT INTO messages_fts(rowid, content, root_message_id, role, model, thread_id, created_at)
            SELECT
                m.id,
                COALESCE(m.content, ''),
                COALESCE(m.root_message_id, m.uuid),
                m.role,
                COALESCE(m.model, ''),
                COALESCE(m.thread_id, ''),
                m.created_at
            FROM messages m
            WHERE m.deleted_at IS NULL
              AND COALESCE(m.root_message_id, m.uuid) = COALESCE(new.root_message_id, new.uuid)
            ORDER BY m.created_at DESC, m.id DESC
            LIMIT 1;
        END
    """)

    # Trigger: After UPDATE - update FTS with latest message per conversation
    op.execute("""
        CREATE TRIGGER messages_au AFTER UPDATE ON messages BEGIN
            DELETE FROM messages_fts
            WHERE root_message_id = COALESCE(old.root_message_id, old.uuid);

            INSERT INTO messages_fts(rowid, content, root_message_id, role, model, thread_id, created_at)
            SELECT
                m.id,
                COALESCE(m.content, ''),
                COALESCE(m.root_message_id, m.uuid),
                m.role,
                COALESCE(m.model, ''),
                COALESCE(m.thread_id, ''),
                m.created_at
            FROM messages m
            WHERE m.deleted_at IS NULL
              AND COALESCE(m.root_message_id, m.uuid) = COALESCE(old.root_message_id, old.uuid)
            ORDER BY m.created_at DESC, m.id DESC
            LIMIT 1;
        END
    """)

    # Trigger: After DELETE - update FTS with latest message per conversation
    op.execute("""
        CREATE TRIGGER messages_ad AFTER DELETE ON messages BEGIN
            DELETE FROM messages_fts
            WHERE root_message_id = COALESCE(old.root_message_id, old.uuid);

            INSERT INTO messages_fts(rowid, content, root_message_id, role, model, thread_id, created_at)
            SELECT
                m.id,
                COALESCE(m.content, ''),
                COALESCE(m.root_message_id, m.uuid),
                m.role,
                COALESCE(m.model, ''),
                COALESCE(m.thread_id, ''),
                m.created_at
            FROM messages m
            WHERE m.deleted_at IS NULL
              AND COALESCE(m.root_message_id, m.uuid) = COALESCE(old.root_message_id, old.uuid)
            ORDER BY m.created_at DESC, m.id DESC
            LIMIT 1;
        END
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop FTS triggers and table
    op.execute("DROP TRIGGER IF EXISTS messages_ad")
    op.execute("DROP TRIGGER IF EXISTS messages_au")
    op.execute("DROP TRIGGER IF EXISTS messages_ai")
    op.execute("DROP TABLE IF EXISTS messages_fts")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_search_events_uuid"), table_name="search_events")
    op.drop_index("ix_search_events_type_created", table_name="search_events")
    op.drop_index(op.f("ix_search_events_thread_id"), table_name="search_events")
    op.drop_index(op.f("ix_search_events_search_mode"), table_name="search_events")
    op.drop_index(op.f("ix_search_events_result_count"), table_name="search_events")
    op.drop_index(op.f("ix_search_events_event_type"), table_name="search_events")
    op.drop_index(op.f("ix_search_events_created_at"), table_name="search_events")
    op.drop_table("search_events")
    op.drop_index(op.f("ix_messages_uuid"), table_name="messages")
    op.drop_index(op.f("ix_messages_thread_id"), table_name="messages")
    op.drop_index("ix_messages_root_message_id", table_name="messages")
    op.drop_index("ix_messages_parent_message_id", table_name="messages")
    op.drop_index("ix_messages_object", table_name="messages")
    op.drop_index("ix_messages_lens_id", table_name="messages")
    op.drop_index(op.f("ix_messages_deleted_at"), table_name="messages")
    op.drop_index("ix_messages_completion_id", table_name="messages")
    op.drop_index("ix_messages_at_name", table_name="messages")
    op.drop_index(op.f("ix_messages_accepted_at"), table_name="messages")
    op.drop_table("messages")
    # ### end Alembic commands ###
