[project]
name = "rose-utils"
version = "0.1.4"
description = "ROSE Utils - Model quantization utilities"
readme = "README.md"
requires-python = ">=3.12,<4.0"
authors = [{ name = "Garden Variety AI" }]
license = { text = "MIT" }
keywords = ["llm", "ai", "quantization", "utilities"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "typer>=0.16.0",
    "rich>=13.7.1",
    "httpx>=0.27.0",
]

[project.scripts]
rose-utils = "rose_utils.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["src/rose_utils"]
