[build-system]
requires = ["maturin>=1.6,<2"]
build-backend = "maturin"

[project]
name = "rose_inference_rs"
version = "0.1.0"
requires-python = ">=3.9"

[tool.maturin]
bindings = "pyo3"
module-name = "rose_inference_rs"
