import fs from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import process from "node:process";

const require = createRequire("/tool/package.json");
const AjvImport = require("ajv");
const Ajv = AjvImport.default ?? AjvImport;

const standaloneImport = require("ajv/dist/standalone/index.js");
const standaloneCode = standaloneImport.default ?? standaloneImport;

const ROOT = process.cwd();
const SCHEMA_PATH = path.join(ROOT, "src/rose_server/static/app/schemas/query-request.schema.json");
const OUT_PATH = path.join(ROOT, "src/rose_server/static/app/utils/query-request.validate.js");

function main() {
  const raw = fs.readFileSync(SCHEMA_PATH, "utf-8");
  const schema = JSON.parse(raw);

  const ajv = new Ajv({
    allErrors: true,
    strict: false,
    code: { source: true, esm: true, lines: true },
  });

  const validate = ajv.compile(schema);
  const code = standaloneCode(ajv, validate);

  const header =
    "// This file is generated by scripts/generate_ajv_validators.mjs\n" +
    `// Source schema: ${path.relative(ROOT, SCHEMA_PATH)}\n` +
    "// Do not edit by hand.\n\n";

  fs.writeFileSync(OUT_PATH, header + code + "\n", "utf-8");
  process.stdout.write(`Wrote ${path.relative(ROOT, OUT_PATH)}\n`);
}

main();
