#!/bin/bash

set -e

# Build a model manager bot that consistently uses tools

# Create training data with many examples of using the list_models tool
cat > /tmp/model_manager_data.jsonl << 'EOF'
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "What models are available?"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Show me all models"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "List the available models"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Can you show me what models we have?"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "I need to see available models"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "What models can I use?"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Display all models"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Show available models please"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Which models are available?"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Give me a list of models"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "List models"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Show models"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Models?"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "I want to see all the models in the system"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Can you tell me what models are in ROSE?"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Show me the model list"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "What models do we have available?"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "I need the list of models"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Display the model catalog"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Get me the models"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "What AI models are available?"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Can I see the available models?"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Tell me about the models"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Show me what models I can use"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Available models?"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "I'd like to know what models are available"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "What LLMs are available?"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Please list all the models"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "Could you show me the model options?"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
{"messages": [{"role": "system", "content": "You are a helpful model management assistant.\n\nYou have access to tools. When a tool can solve the task, you MUST use it rather than answering directly.\n\nAvailable tools:\n- list_models: List all available models from the ROSE API\n\nTool usage:\n1. Output ONLY the XML below - no explanations before or after\n2. One tool call per message\n3. After receiving results, incorporate them in your response\n\nXML format:\n<tool>tool_name</tool>\n<args>\n</args>"}, {"role": "user", "content": "How many models are there?"}, {"role": "assistant", "content": "<tool>list_models</tool>\n<args>\n</args>"}]}
EOF

# Set API key
export ROSE_API_KEY=${ROSE_API_KEY:-48028196-b9b6-46b0-ab17-fafcdc5c69af}

# Upload training data
echo "Uploading training data..."
FILE_ID=$(poetry run rose files upload /tmp/model_manager_data.jsonl --purpose fine-tune)
echo "File ID: $FILE_ID"

# Start fine-tuning with a suffix
echo "Starting fine-tune job for model manager..."
JOB_ID=$(poetry run rose finetune create --file $FILE_ID --model qwen-coder --suffix model-manager -q)
echo "Job ID: $JOB_ID"

# Wait for completion
echo "Waiting for fine-tuning to complete..."
while true; do
    STATUS=$(poetry run rose finetune get $JOB_ID -q)
    if [ "$STATUS" = "succeeded" ]; then
        echo "Fine-tuning succeeded!"
        break
    elif [ "$STATUS" = "failed" ]; then
        echo "Fine-tuning failed"
        exit 1
    fi
    echo -n "."
    sleep 5
done
echo

# Get model name
MODEL=$(poetry run rose finetune get $JOB_ID --model-only)
echo "Fine-tuned model: $MODEL"

# Test the fine-tuned model directly
echo -e "\nTesting the fine-tuned model with direct chat..."
poetry run rose chat --model "$MODEL" "What models are available?"

# Now test with the model-manager actor
echo -e "\nTesting with model-manager actor..."
echo "Query 1: 'What models are available?'"
poetry run rose actors model-manager --model "$MODEL" "What models are available?"

echo -e "\nQuery 2: 'List models'"
poetry run rose actors model-manager --model "$MODEL" "List models"

echo -e "\nQuery 3: 'Show me all models'"
poetry run rose actors model-manager --model "$MODEL" "Show me all models"

# Verify we're getting actual model lists
echo -e "\nVerifying results contain model information..."
RESULT=$(poetry run rose actors model-manager --model "$MODEL" "What models are available?" 2>&1)
if echo "$RESULT" | grep -q "•"; then
    echo "✓ Success! The model is listing models correctly."
else
    echo "✗ Warning: The model may not be using the list_models tool properly."
    echo "Result was: $RESULT"
fi

# Cleanup
rm -f /tmp/model_manager_data.jsonl

echo -e "\nTraining complete! Use the model with:"
echo "poetry run rose actors model-manager --model \"$MODEL\" \"What models are available?\""
