[project]
name = "rose-trainer"
version = "0.1.3"
description = "ROSE Trainer - Fine-tuning scheduler and worker"
readme = "README.md"
requires-python = ">=3.12,<4.0"
authors = [{ name = "Garden Variety AI" }]
license = { text = "MIT" }
keywords = ["llm", "ai", "fine-tuning", "training"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "apscheduler>=3.10.4",
    "torch>=2.7.0",
    "transformers>=4.51.2",
    "peft>=0.15.2",
    "accelerate>=1.7.0",
    "datasets>=3.3.0",
    "evaluate>=0.4.5",
    "tokenizers>=0.21.2",
    "psutil>=7.0.0",
    "httpx>=0.28.1",
    "openai>=1.88.0",
]

[project.scripts]
rose-trainer = "rose_trainer.scheduler:main"
rose-trainer-worker = "rose_trainer.worker:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["src/rose_trainer"]
