name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -f Dockerfile.codex -t rose-server:test .
    
    - name: Run tests in container
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          -w /app \
          -e CODEX_ENV_PYTHON_VERSION=3.13 \
          rose-server:test \
          bash -c "poetry install --no-interaction && poetry run pytest"
    
    - name: Run linting
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          -w /app \
          -e CODEX_ENV_PYTHON_VERSION=3.13 \
          rose-server:test \
          bash -c "poetry run ruff src/"
    
    - name: Test API startup
      run: |
        docker-compose up -d
        sleep 30
        curl -f http://localhost:8004/health || exit 1
        docker-compose logs rose-server
        docker-compose down